### ISSUE TITLE
Paper #3 ‘Praise the people or praise the place’: migration and skills

### ISSUE THREAD

**Issue by j-jayes** [j-jayes/SC-1930#2]
## Paper idea

Is it the person or the place that results in better development outcomes? Is it true that just moving to a city raises your productivity, or if smart people stayed in the countryside would they contribute as much to their own community?

The purpose of the paper is to attempt to answer this question, using as a case study the electrification of Sweden that took place in the first half of the 20th century. We exploit the connection of parishes in Sweden along the line between two large hydroelectric power plants as a shock that provided these parishes a high-quality, stable, and strong electricity connection prior to their otherwise comparable neighbouring parishes. 

Data is a cross-section in time, but we know where people were born and where they lived in the last 5 years if they didn't live at home. We can do some descriptive statistics of where the people moved from.

The question is: if you're shocked with electricity, are you more likely or less likely to migrate from your parish of birth, compared to a control group who does not receive the shock?

### Questions

Questions to think about:

- [ ] How do we define exposure to electricity?

Kerstin mentioned that if someone is an adult in the 1930 census, who was at least 20 years of age, then they will have been shocked by electrification when the grid was connected in 1920. Right?

### Controls

What do we want to use as controls?

- Age
- Parish FE?
- HISCO code?
- Skill groupings

Questions to ask next:

- What happens to them if they do move?
- Do they get higher incomes than their parish of birth on average? Show some density distribution.

TODO for preparing the dataset for analysis:

- [x] Check 1930 census overlap with electricity parishes. Two ways. Codes and Geography.
- [x] Binary variables for: Age of some threshold for adulthood in 1930. Parish of birth same as parish of current residence. 
- [x] Some descriptive statistics of these variables, by electricity parish and by county. 
- [x] 1930 census contains occupational strings but not HISCO codes. Prior censuses have occupational strings and HISCO codes.

### To remember

The unit of analysis is the individual level, while the treatment is at the parish level, so we must cluster our SEs at the parish level. 

### Literature review planning

- [ ] Find a template
- [ ] Start on the review and keep it in a useful place

### Occupational classification.

In the 1930 census, there are 87,099 different listed occupations. We need to classify these into a manageable number of groups so that we can work with them. 

#### Lookup table

The first attempt to do this used the list of occupations from 1910 and associated HISCO codes as a simple lookup table. 

There were a few problems with this. First, there was no one-to-one mapping from string to code. For example;

In the case of single-word occupations, 

- the occupation "Jungfru" is coded as:
- - HISCO 54020 - "House servants nfs and maids" 
- - HISCO 99150 - "Worker nfs" and,
- - HISCO 99999 - missing.

In the case of multiple occupations listed in the field, 

- the occupation "Arbetare Arrendator f." is coded as HISCO 99150 - "Worker nfs" but
- the occupation"Arbetare Arrendator f.d." is coded as HISCO 61110 - "General farmers and farmers nfs"

Here the "f." and "f.d." abbreviate före detta (former). Clearly, after removing the abbreviations it, the occupational strings would be the same but be coded to different HISCOs.

The second issue is that of the 87,099 occupations in the 1930 census there was only an overlap of 20,000 occupational strings in the 1910 census.

To overcome the first of these issues it would be possible to simply count the most common classification in the cases where there is a conflict, and then use the most common one as the 'truth'. For example, "Jungfru" was most commonly coded as HISCO 54020 - "House servants nfs and maids" in the 1910 census. 

In addition, it is possible to create a variable to flag the former occupation by detecting instances of "f." and "f.d." abbreviating före detta, creating a new column with an indicator for these and then removing them from the original. 

#### Machine learning approach 1

The second method that I tried to implement was a machine learning classifier, using as training data the 1910 census, coding from HISCO to 5 occupational groups, and then predicting the occupational group from the occupational string in 1930. I hoped that the algorithm would recognize the different parts of words associated with the different social classes and then be good at classifying them. Sadly it was not very successful, such that the fishermen were assigned as skilled workers, etc.

#### Rules based approach.

I spent this week with the help of project assistant Anders Larsson condensing the list of 87,099 occupations down to just 7,013 common occupations. This is more manageable, and we intend to continue to condense these down.

The process to condense these down is documented in a codebook and can be replicated.

It was to:

1. flag previous occupation indicated with "f.d."
2. flag temporary occupation indicated with "f.n"
3. flag widows indicated by the presence of "änka"
4. flag wife indicated by "hustru"
5. flag for "Undantag"
6. separate the place of work from the occupation, e.g. for "Hushållerska hos Månsson" create a new column with "hos Månsson" (interestingly there are fully 200 people who indicate working for bearing manufacturer S.K.F. after it was established in 1907.
7. flagging multiple occupations, e.g. "Författare Teater- och litteraturkritiker" and separating just the first title, "Författare"
8. flag an indicator for without work, e.g. "Utan anställning Bokhandelsidkare f.d"
9. flag academic titles including "kand.", "lic.", "mag.", "doktor" and "professor" in the faculties of "Fil.", "Teol.", and "Ing."
The result was a collapsing of the different occupations from 87,099 different strings to just 7,013. This is a lot more manageable.

#### Machine learning approach 2

After completing the cleaning process described above, I hope to have a manageable number of occupations, consisting of one word. Then I will attempt the machine learning approach from 1 with some modified techniques, including using age and sex as a predictor in the model, along with the text of the occupation. I hope that this will allow a larger number of groups to be assigned, making the analysis that will follow more informative. 

Next steps:

- [x] Try new ML model with transformer
- [x] Write up report on ML classification
- [x] Check the electrification committee reports for prices and generation capacity in treatment and control group

Next steps after meeting on 28th of October

- [x] Get relation and status variables from 1910 census
- [x] Crosswalk to get the hisclass from hisco
- [ ] Check if crosswalk can be done without contradiction
- [x] Check where to get hisclass from

**Next steps after meeting on 8 November**

Think about matching people between censuses - when we can do this, what is the mechanism we expect?

People versus place. Who benefitted? If we know that people who stayed behind in electricity parishes - this is great.

- staying in your parish of birth is bad. it means something about your skils. if staying in your parish of birth in an electricity parish makes things less bad, this is great.

- [ ] Test that for the parishes we have in the 1930 census, that the pre-trends are the same in 1900 - need to do balance tests.
- [ ] Validate hisclass with Björn.
- [x] think about how to deal with zeros in income data
- [ ] add effect on income at mean and median in plots
- [ ] do a statistical test for the difference in distributions - non-parametric tests
- [ ] do some regressions at the parish level where gini is the outcome - then break up gini by migration status
- [ ] repeat regressions from appendix in MPTP - looking at share in agriculture or 
- [ ] break up 1930 census by skill groups and redo regressions. try a quantile regression

Side quests

- [ ] See who the elite who moved out are
- [ ] break up results by farm workers vs farm owners. Repeat the stacked column graph with farm workers and farm owners
- [ ] do we find marginal effects that differ by amount of industry present in parish (find data on industry share in parish - Kerstin's database)
- [ ]

**Comment by j-jayes** [comment]
## Phase 1.1

Think about identifying individuals who receive treatment more clearly. 

Make use of census variables like "moved in year" and "moved in location"

**Comment by j-jayes** [comment]
# Digitizing electrification reports

- [ ] Älvsborg
- [ ] Blekinge
- [ ] Gävleborg
- [ ] Goteborgs och Bohus
- [ ] Gotland
- [ ] Halland
- [ ] Jämtland
- [ ] Jönköping
- [ ] Kalmar
- [ ] Koppaberg
- [ ] Kristianstad
- [ ] Kronobergs
- [ ] Norrbottens Lan
- [ ] Örebro
- [ ] Östergötland
- [ ] Skaraborgs län
- [ ] Södermanland

**Comment by j-jayes** [comment]
## Regression

Reg electricity consumption on being on the Western Line. 

Add some FEs. 

To show that there is a strong effect of being on the line. 

Control for hisclass in 1900 - that would control for any potential differences. 

Hisclass in 1930 - can be an outcome variable - tells us how much of the income effect is due to changing jobs. we want to look at how the occupational distribution is changing.

**Comment by j-jayes** [comment]
## Methodology 

A cross-section where we control for time-varying characteristics prior to the shock.

**Comment by j-jayes** [comment]
Gray - no hollowing out in the whole economy. 

Lawrence Katz - within the industry there is hollowing out but across the whole economy.

Structural change - how electricity has played out - for Norway - electricity increased the share of the industry. 

For the US - Severnini - finds that rural parishes specialized in agriculture.

skill distribution - different sectors - and then sectoral specialization. 

Cross section - suitability indicators.

**Comment by j-jayes** [comment]
Make Stayers in the Omitted category -

Non-mover and non-electricity should be base category. Then we have one coefficient 

Include one regression where we compare only people born in electricity parishes to those not born there.

Then we decompose this - the positively selected who can move, then those who can stay there.

Number 1 regression - born in electricity parish -

**Comment by j-jayes** [comment]
Smallest group should be the only group

**Comment by j-jayes** [comment]
Sub analysis - divded between men and women

What group do we want to estimate on?

**Comment by j-jayes** [comment]
Cut ages - prime aged males only

**Comment by j-jayes** [comment]
Interaction with gender

**Comment by j-jayes** [comment]
1. Smaller subgroup - 1925 location - rule out that they moved away. Can be addressed with 1925 data.

2. Too old for treatment. Use 1910 census. We observe them again at 40 or 50.

**Comment by j-jayes** [comment]
Kerstin: really interesting to get more clear into the mechanisms on the individual level.

Same specification but different outcome variables. 

- dummy on individuals born in electricity parishes - are they more likely to move away. (no job, or skills better used somewhere else)
- More likely to change jobs

Do they behave differently?

List of jobs that are new to 1930 census. Dummy for new job. Still be useful. 
Jobs are electricity-related.

List of all electricity jobs - dummy out of that. 

A good first regression in the appendix - shows that this treatment variable affects what we expect it to.

Both directly related jobs - and factory jobs - 

New jobs - all are skilled - lower and medium-skilled. 

Upgrading effect - goes against the American literature.

Use education as an outcome variable. Almost everyone has primary education. Create a variable for secondary education. Dummy for "More than 6 years of schooling"

**Comment by j-jayes** [comment]
Do you get more skilled jobs without more education - or does it go through the other way?

"Passive winners" you are just around the industry - not in it yourself. 

You have a productivity affect - and a demand effect. 

Separate out by electricity effect.

If you change job - does the income effect come through being in an electricity parish?

**Comment by j-jayes** [comment]
One part - talk about the individuals - different outcomes on the individual level. 

Second part - what happens at the parish level - interesting to know some things about the composition of jobs in these parishes - general level - is the share of electricity related jobs larger in electricity parishes? 

If the turnover between movers and stayers is higher in electricity parishes. Gross flow of movers. Share of people born outside of the parish. Share of stayers - immigrant share and outmigrant share. 

Literature on industry churning.

**Industry churning** - how many people are moving in and out of different jobs over time. 

1925 - 1930. Change jobs in parish vs Change jobs between parishes.

**Comment by j-jayes** [comment]
Was it an issue to find the right competence - who took these new jobs? Were the new jobs filled with people they had access to?

Are they recruited locally? Education requirements for new jobs - what was the local education like?

Get the education requirements from the 1930 census. 

Knowing who had these jobs - is NB.

Where were the schools for these types of jobs?

**Comment by j-jayes** [comment]
Email Jakob asking about the links and the new jobs -

**Comment by j-jayes** [comment]
## Final paper planning

Split it into two papers:

spend time showing the treatment is exogenous - controls in 1910.

Focus more on the total labour market - where do the people 

Focus on income - outcome and controls are fine - the only thing the reviewer would complain about is the shock.



Pre-trend analysis we introduce if the reviewers ask for it.

**Comment by j-jayes** [comment]
Do we do the individual paper first? Yes

So the one paper is the individual effects - with a panel.

The second paper looks at the differences in the distribution.

Focus on making the shock super clear in this individual focussed paper.

**Comment by j-jayes** [comment]
What can we control for in the first paper?

- Household fixed effects. Not a panel, it's a cross-section with dummies.
- link individuals back to 1910, 

For occupation, we can have an individual panel.

link to 1910 and 1900, get the household identifier, run the same regressions, then run the regression for occupation.

We need to think about the subset of individuals - they are siblings who lived in an electricity parish they must be living in 1910, they are at least 12 when they are shocked - they must be siblings. 


"Why don't you make a panel?"
- we only observe income in 1930.
- We can find treatment for one who moves and one who stays.

We make the panel, and we use occupational income score - FE regression, control for selection, we control for 

If they have an occupation in 1900 - they are at least 15.


1910, 1925 and 1930. 1910 to 1925 is the pre-trend.

The pre-trend is whether they are different.

## **Add a control for occupation in 1910.** 

- Show that this is treated
- then do occupational upgrading between 1925 and 1930.

If we find something then it's good.

individual paper with job upgrading.

Controlling for the occupation in 1910, then we have a reference for the occupational trajectory. We see if they changed jobs, electricity-related jobs,

**Comment by j-jayes** [comment]
This first paper is just individual effects.

The second paper looks at the skill distribution.

**Comment by j-jayes** [comment]
## Gender

Poignant cites papers in South Africa that found electricity provision increased women's labour force participation - can do like a PSM effect and look for women who weren't working and then who did have an income.

**Comment by j-jayes** [comment]
### IV restriction

Spend time explaining why the provision of electricity wasn't related to the provision of e.g. roads at the same time - in that infrastructure projects in developing countries today do

**Comment by j-jayes** [comment]
## Making a panel

First I want to look at the relatively few people in my 4x grid who are born in an electricity parish and stay and look at the kinds of jobs that they have - can make a panel to look back in time and also just look at what they had in 1925 from the 1930 census.

**Comment by j-jayes** [comment]
## Discuss in literature review why the question is important.

In the poignant paper they say, "well the first seminal papers on the subject said this, later papers found no effect and blamed the IV exclusion restriction, this is why ours is better"
